### ISSUE TITLE
Generic Suggestions/Issues

### ISSUE THREAD

**Issue by jiveshkalra** [imdigitalashish/NamasteScreen#1]
- [x] **No App Icon or Title**: The app is just called "Android Launcher" with default android icon
- [x] **App can be closed easily**: Currently , If you close the app , you can get out of the NamasteScreen ecosystem and continue using your phone like normal , 
a Better approach might be to make it as **Android Home Screen** , like minimalistic phone does or PW LearnOS (on Playstore) does.
So even if they try to close the application , since its set as Home Screen , it will open again and again
- [x] **Adding an in-built App time tracker and app time controller**

**Comment by imdigitalashish** [comment]
Nice Suggestions.

No App Icon or Title: Yes you can add and App name would be Namaste Screen

App can be closed and that: It's registered as a launcher, so android has a native do that, we don't want to control phones like PW learnOS. So maybe you can add a settings to click a button which sends them to launcher choosing screen and then select Namaste Screen as default Launcher

3rd feature is already in native android, just like I've implemented Screen Time, you can get data from OS 

Let me know, if you have more doubts.

**Comment by jiveshkalra** [comment]
Got it working as a launcher from settings , 
just a minor UX recommendation , 
how about instead of having apps at the bottom to click, we instead have a setup like minimalistic phone , in which we swipe right to get all our apps and also have a search option directly baked into it for quick accessibility or something similar to this?
(also for some reason the bottom apps button doesnt work some times idk why, its abit unresponsive)

**Comment by imdigitalashish** [comment]
Got it... Let me look at Compose Internal codes may be there I get to know what's missing... !

**Comment by imdigitalashish** [comment]
All these are implemented now !
